# Generated by Django 4.2 on 2023-04-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capturista',
            fields=[
                ('CURP_Cap', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CT',
            fields=[
                ('CT', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_CT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CURP', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Ap_Pat', models.CharField(max_length=50)),
                ('Ap_Mat', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=3)),
                ('Escolaridad', models.CharField(max_length=50)),
                ('Funcion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Cve_Ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.ct')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('Hora_fin', models.CharField(max_length=5)),
                ('CURP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.usuario')),
                ('CURP_Cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.capturista')),
                ('id_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.tramite')),
            ],
        ),
    ]
