# Generated by Django 4.2 on 2023-04-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='hora',
        ),
        migrations.AddField(
            model_name='visita',
            name='Hora_ini',
            field=models.CharField(default='03:36', max_length=50),
        ),
    ]
