# Generated by Django 4.2 on 2023-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_visita_dia_remove_visita_hora_visita_hora_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Hora_ini',
            field=models.CharField(default='03:37', max_length=50),
        ),
    ]
