# Generated by Django 4.2 on 2023-04-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_visita_hora_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Hora_fin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visita',
            name='Hora_ini',
            field=models.CharField(default='04:02', max_length=50),
        ),
    ]
