# Generated by Django 4.2 on 2023-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_visita_hora_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Hora_ini',
            field=models.CharField(default='04:08', max_length=50),
        ),
    ]
