# Generated by Django 4.2 on 2023-04-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_visita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Fecha',
            field=models.CharField(max_length=50),
        ),
    ]
