# Generated by Django 4.2 on 2023-05-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_alter_visita_options_alter_visita_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={},
        ),
        migrations.AlterModelTable(
            name='visita',
            table=None,
        ),
    ]
